# Generated by Django 5.0 on 2024-02-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_passwordreset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
